namespace ManagedCode.Presidio.Analyzer;

/// <summary>
/// Placeholder for artifacts generated by an NLP engine. Will be expanded as part of the migration.
/// </summary>
public sealed class NlpArtifacts(string language, IReadOnlyList<Token>? tokens = null)
{
    public string Language { get; } = language;

    public IReadOnlyList<Token> Tokens { get; } = tokens ?? [];
}
